name: ephermal kubernetes deploy
on:
  pull_request:
    types: [labeled,unlabeled,closed]

jobs:
  deploy:
    if: github.event.label.name == 'test' && github.event.action == 'labeled'
    runs-on: runner-set
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: docker installation
        run: |
          #Add Docker's official GPG key:
          sudo apt update
          sudo apt install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

          # Add the repository to Apt sources:
          sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
          Types: deb
          URIs: https://download.docker.com/linux/ubuntu
          Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
          Components: stable
          Architectures: $(dpkg --print-architecture)
          Signed-By: /etc/apt/keyrings/docker.asc
          EOF

          sudo apt update
          sudo apt install docker-ce docker-ce-cli containerd.io -y

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: lab/node-test-app
          push: true
          tags: nihaltp/nodeapp:pr-${{ github.event.pull_request.number }}-${{ github.sha }}
      - name: install vcluster CLI
        run: |
          curl -L -o vcluster "https://github.com/loft-sh/vcluster/releases/latest/download/vcluster-linux-amd64" && sudo install -c -m 0755 vcluster /usr/local/bin && rm -f vcluster
      - name: install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: create vcluster
        working-directory: lab/node-test-app
        run: bash deploy-pr-env.sh
        env:
          PR_NUM: "${{ github.event.pull_request.number }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_TAG: nihaltp/nodeapp:pr-${{ github.event.pull_request.number }}-${{ github.sha }}
      - name: post comment
        run: |
          PR_NUM=${{ github.event.pull_request.number }}
          BODY="App is running at http://pr-${PR_NUM}.local:8080"
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2026-03-10" \
          https://api.github.com/repos/"${{ github.repository }}"/issues/"${PR_NUM}"/comments \
          -d "{\"body\":\"${BODY}\"}"
    
  destroy:
    if: (github.event.action == 'unlabeled' && github.event.label.name == 'test') || github.event.action == 'closed'
    runs-on: runner-set
    steps:
      - name: install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - name: destoy vcluster
        run: |
          PR_NUM="${{ github.event.pull_request.number }}"
          VCLUSTER_NAME="pr-${PR_NUM}"
          NAMESPACE="vcluster-pr-${PR_NUM}"
          if kubectl get namespace "${NAMESPACE}" >/dev/null 2>&1; then
            echo "namespace '${NAMESPACE}' found,deleting'"
            kubectl delete namespace "${NAMESPACE}"
          else
            echo "namespace '${NAMESPACE}' not found,aborting deletion"
          fi
        

    
